// Harness Research MCP Server — Interactive Setup Wizard
// Guides users through API key configuration on first use

import fs from "node:fs"
import path from "node:path"
import { createInterface } from "node:readline"
import { CONFIG_DIR, ENV_PATH, ensureConfigDir, getPlatformCapabilities } from "../utils/config.js"

function createPrompt(): { ask: (question: string) => Promise<string>; close: () => void } {
  const rl = createInterface({ input: process.stdin, output: process.stdout })
  return {
    ask: (question: string) =>
      new Promise<string>(resolve => {
        rl.question(question, answer => resolve(answer.trim()))
      }),
    close: () => rl.close(),
  }
}

export async function setupWizard(): Promise<void> {
  const prompt = createPrompt()

  console.log("")
  console.log("╔══════════════════════════════════════════════════════╗")
  console.log("║       Harness Research MCP — Setup Wizard           ║")
  console.log("║  Multi-source deep research with CRAAP evaluation   ║")
  console.log("╚══════════════════════════════════════════════════════╝")
  console.log("")

  // Step 1: Environment check
  console.log("── Step 1: Environment Check ──")
  const caps = await getPlatformCapabilities()
  console.log(`  OS: ${caps.os}`)
  console.log(`  Node.js: ${process.version}`)
  console.log(`  HTML output: ✅`)
  console.log(`  DOCX output: ✅`)
  console.log(`  PDF output: ${caps.pdf ? "✅ (Puppeteer available)" : "❌ (macOS + Puppeteer required)"}`)
  console.log("")

  // Step 2: API Key configuration
  console.log("── Step 2: API Key Configuration ──")
  console.log("")
  console.log("  You need at least ONE search engine key and ONE LLM key.")
  console.log("")

  const envVars: Record<string, string> = {}

  // Search keys
  console.log("  [SEARCH ENGINES] (at least one required)")
  console.log("")

  const tavilyKey = await prompt.ask("  Tavily API Key (https://tavily.com, press Enter to skip): ")
  if (tavilyKey) envVars.TAVILY_API_KEY = tavilyKey

  const braveKey = await prompt.ask("  Brave Search API Key (https://brave.com/search/api, press Enter to skip): ")
  if (braveKey) envVars.BRAVE_API_KEY = braveKey

  if (!tavilyKey && !braveKey) {
    console.log("")
    console.log("  ⚠ WARNING: No search engine key provided.")
    console.log("  You need at least one (Tavily or Brave) for research to work.")
    const cont = await prompt.ask("  Continue anyway? (y/N): ")
    if (cont.toLowerCase() !== "y") {
      prompt.close()
      process.exit(1)
    }
  }

  console.log("")
  console.log("  [RESEARCH MODEL] (required)")
  console.log("  Kimi K2.5 through OpenRouter: moonshotai/kimi-k2.5")
  console.log("")

  const orKey = await prompt.ask("  OpenRouter API Key (https://openrouter.ai): ")
  if (orKey) envVars.OPENROUTER_API_KEY = orKey

  // Optional keys
  console.log("")
  console.log("  [OPTIONAL DATA SOURCES] (press Enter to skip all)")
  console.log("")

  const tushareKey = await prompt.ask("  Tushare Token (https://tushare.pro — Chinese financial data): ")
  if (tushareKey) envVars.TUSHARE_TOKEN = tushareKey

  const ncbiKey = await prompt.ask("  NCBI API Key (https://ncbiinsights.ncbi.nlm.nih.gov — PubMed): ")
  if (ncbiKey) envVars.NCBI_API_KEY = ncbiKey

  const youtubeKey = await prompt.ask("  YouTube Data API Key (YouTube search, transcripts use public captions when available): ")
  if (youtubeKey) envVars.YOUTUBE_API_KEY = youtubeKey

  const xaiKey = await prompt.ask("  xAI API Key (X/Twitter search synthesis): ")
  if (xaiKey) envVars.XAI_API_KEY = xaiKey

  // Step 3: Write config
  console.log("")
  console.log("── Step 3: Saving Configuration ──")
  ensureConfigDir()

  const envContent = Object.entries(envVars)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n")

  fs.writeFileSync(ENV_PATH, `# Harness Research MCP — API Keys\n# Generated by setup wizard\n\n${envContent}\n`)
  console.log(`  Config saved to: ${ENV_PATH}`)

  // Step 4: Smoke test
  console.log("")
  console.log("── Step 4: Connection Test ──")

  // Test search
  const hasSearch = envVars.TAVILY_API_KEY || envVars.BRAVE_API_KEY
  if (hasSearch) {
    try {
      if (envVars.TAVILY_API_KEY) {
        const resp = await fetch("https://api.tavily.com/search", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            api_key: envVars.TAVILY_API_KEY,
            query: "test",
            max_results: 1,
          }),
          signal: AbortSignal.timeout(10000),
        })
        console.log(`  Tavily API: ${resp.ok ? "✅ Connected" : `❌ HTTP ${resp.status}`}`)
      }
      if (envVars.BRAVE_API_KEY) {
        const resp = await fetch("https://api.search.brave.com/res/v1/web/search?q=test&count=1", {
          headers: { "X-Subscription-Token": envVars.BRAVE_API_KEY },
          signal: AbortSignal.timeout(10000),
        })
        console.log(`  Brave API: ${resp.ok ? "✅ Connected" : `❌ HTTP ${resp.status}`}`)
      }
    } catch (e: any) {
      console.log(`  Search API test failed: ${e.message}`)
    }
  }

  // Test LLM
  const llmKey = envVars.OPENROUTER_API_KEY
  if (llmKey) {
    try {
      const resp = await fetch("https://openrouter.ai/api/v1/models", {
        headers: { Authorization: `Bearer ${llmKey}` },
        signal: AbortSignal.timeout(10000),
      })
      console.log(`  OpenRouter API: ${resp.ok ? "✅ Connected" : `❌ HTTP ${resp.status}`}`)
    } catch (e: any) {
      console.log(`  LLM API test failed: ${e.message}`)
    }
  }

  // Step 5: Output MCP config
  console.log("")
  console.log("── Step 5: MCP Client Configuration ──")
  console.log("")
  console.log("  ✅ Setup complete! Copy the config below into your AI agent:")
  console.log("")
  console.log("  ┌─ Claude Desktop / Cursor / OpenCode ─────────────────┐")
  console.log('  │ {                                                     │')
  console.log('  │   "mcpServers": {                                     │')
  console.log('  │     "harness-research": {                             │')
  console.log('  │       "command": "npx",                               │')
  console.log('  │       "args": ["-y", "harness-research-mcp"]          │')
  console.log('  │     }                                                 │')
  console.log('  │   }                                                   │')
  console.log('  │ }                                                     │')
  console.log("  └───────────────────────────────────────────────────────┘")
  console.log("")
  console.log("  ┌─ OpenClaw ───────────────────────────────────────────┐")
  console.log("  │ openclaw mcp set harness-research \\                  │")
  console.log("  │   '{\"command\":\"npx\",\"args\":[\"-y\",\"harness-research-mcp\"]}' │")
  console.log("  └───────────────────────────────────────────────────────┘")
  console.log("")

  const outputFormats = ["HTML ✅", "DOCX ✅"]
  if (caps.pdf) outputFormats.push("PDF ✅")
  else outputFormats.push("PDF ❌ (macOS only)")
  console.log(`  Available output formats: ${outputFormats.join("  ")}`)
  console.log("")

  prompt.close()
}
