// Harness Research MCP Server — Interactive Setup Wizard
// Guides users through local credential configuration.

import fs from "node:fs"
import { createInterface } from "node:readline"
import { ENV_PATH, ensureConfigDir } from "../utils/config.js"

function createPrompt(): { ask: (question: string) => Promise<string>; close: () => void } {
  const rl = createInterface({ input: process.stdin, output: process.stdout })
  return {
    ask: (question: string) =>
      new Promise<string>(resolve => {
        rl.question(question, answer => resolve(answer.trim()))
      }),
    close: () => rl.close(),
  }
}

export async function setupWizard(): Promise<void> {
  const prompt = createPrompt()

  console.log("")
  console.log("╔══════════════════════════════════════════════════════╗")
  console.log("║       Harness Research MCP — Setup Wizard           ║")
  console.log("║  Topic-only deep research returning Markdown inline ║")
  console.log("╚══════════════════════════════════════════════════════╝")
  console.log("")

  console.log("── API Key Configuration ──")
  console.log("  Required model route: Kimi K2.6 through Alloy Runtime / Fireworks")
  console.log("  Model: fireworks-ai/accounts/fireworks/models/kimi-k2p6")
  console.log("")

  const envVars: Record<string, string> = {}

  const alloyUrl = await prompt.ask("  Alloy Runtime API URL: ")
  if (alloyUrl) envVars.ALLOY_RUNTIME_API_URL = alloyUrl

  const alloyKey = await prompt.ask("  Alloy Runtime API Key: ")
  if (alloyKey) envVars.ALLOY_RUNTIME_API_KEY = alloyKey

  console.log("")
  console.log("  [OPTIONAL SOURCE CREDENTIALS] (press Enter to skip)")
  console.log("  Missing optional sources degrade gracefully; Hermes env fallback is also supported.")
  console.log("")

  const tavilyKey = await prompt.ask("  Tavily API Key: ")
  if (tavilyKey) envVars.TAVILY_API_KEY = tavilyKey

  const braveKey = await prompt.ask("  Brave Search API Key: ")
  if (braveKey) envVars.BRAVE_API_KEY = braveKey

  const youtubeKey = await prompt.ask("  YouTube Data API Key: ")
  if (youtubeKey) envVars.YOUTUBE_API_KEY = youtubeKey

  const xaiKey = await prompt.ask("  xAI API Key (optional; Hermes xAI OAuth fallback can be used): ")
  if (xaiKey) envVars.XAI_API_KEY = xaiKey

  const tushareKey = await prompt.ask("  Tushare Token: ")
  if (tushareKey) envVars.TUSHARE_TOKEN = tushareKey

  const ncbiKey = await prompt.ask("  NCBI API Key: ")
  if (ncbiKey) envVars.NCBI_API_KEY = ncbiKey

  console.log("")
  console.log("── Saving Configuration ──")
  ensureConfigDir()

  const envContent = Object.entries(envVars)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n")

  fs.writeFileSync(ENV_PATH, `# Harness Research MCP — API Keys\n# Generated by setup wizard\n\n${envContent}\n`)
  console.log(`  Config saved to: ${ENV_PATH}`)
  console.log("")
  console.log("  Top-level MCP input schema is intentionally topic-only:")
  console.log('  { "topic": "..." }')
  console.log("")
  console.log("  Output is always the finished Markdown report returned inline.")
  console.log("")

  prompt.close()
}
